<?php

declare(strict_types=1);

namespace Keboola\StorageDriver\BigQuery\Handler\Bucket\Create;

use Google\ApiCore\ApiException;
use Google\Cloud\BigQuery\AnalyticsHub\V1\DestinationDataset;
use Google\Cloud\BigQuery\AnalyticsHub\V1\DestinationDatasetReference;
use Google\Protobuf\Internal\Message;
use Keboola\StorageDriver\BigQuery\CredentialsHelper;
use Keboola\StorageDriver\BigQuery\GCPClientManager;
use Keboola\StorageDriver\BigQuery\NameGenerator;
use Keboola\StorageDriver\Command\Bucket\GrantBucketAccessToReadOnlyRoleCommand;
use Keboola\StorageDriver\Command\Bucket\GrantBucketAccessToReadOnlyRoleResponse;
use Keboola\StorageDriver\Contract\Driver\Command\DriverCommandHandlerInterface;
use Keboola\StorageDriver\Credentials\GenericBackendCredentials;
use Keboola\StorageDriver\Shared\Driver\Exception\Exception;

final class GrantBucketAccessToReadOnlyRoleHandler implements DriverCommandHandlerInterface
{
    public GCPClientManager $clientManager;

    public function __construct(GCPClientManager $clientManager)
    {
        $this->clientManager = $clientManager;
    }

    /**
     * @inheritDoc
     */
    public function __invoke(
        Message $credentials,
        Message $command,
        array $features,
        Message $runtimeOptions,
    ): ?Message {
        assert($credentials instanceof GenericBackendCredentials);
        assert($command instanceof GrantBucketAccessToReadOnlyRoleCommand);

        assert($runtimeOptions->getMeta() === null);

        assert(
            $command->getPath()->count() === 4,
            'GrantBucketAccessToReadOnlyRoleCommand.path is required and size must equal 4'
        );
        assert(
            $command->getDestinationObjectName() !== '',
            'GrantBucketAccessToReadOnlyRoleCommand.getDestinationObjectName is required'
        );

        assert(
            $command->getStackPrefix() !== '',
            'GrantBucketAccessToReadOnlyRoleCommand.getStackPrefix is required'
        );

        [
            $projectId,
            $location,
            $dataExchangerId,
            $listingId,
        ] = $command->getPath();
        $listingName = $this->clientManager->getAnalyticHubClient($credentials)
            ->listingName(
                $projectId,
                $location,
                $dataExchangerId,
                $listingId
            );

        // This is the name of a bucket created in the target project that represents an external bucket
        $registeredBucketName = $command->getDestinationObjectName();

        $projectCredentials = CredentialsHelper::getCredentialsArray($credentials);

        $analyticHubClient = $this->clientManager->getAnalyticHubClient($credentials);

        $nameGenerator = new NameGenerator($command->getStackPrefix());

        // 1. Create new name for dataset
        // In BQ, the linked dataset is physically created in the target project,
        // so we have to generate it from the name we got in the request.
        $newBucketDatabaseName = $nameGenerator->createObjectNameForBucketInProject(
            $registeredBucketName,
            $command->getBranchId()
        );

        $datasetReference = new DestinationDatasetReference();
        $datasetReference->setProjectId($projectCredentials['project_id']);
        $datasetReference->setDatasetId($newBucketDatabaseName);

        $destinationDataset = new DestinationDataset([
            'dataset_reference' => $datasetReference,
            'location' => GCPClientManager::DEFAULT_LOCATION,
        ]);

        try {
            // 2. Then we just need to subscribe to the listing that the user created
            // according to the instruction before he called the bucket registration.
            $analyticHubClient->subscribeListing($listingName, [
                'destinationDataset' => $destinationDataset,
            ]);
        } catch (ApiException $e) {
            throw SubscribeListingPermissionDeniedException::handlePermissionDeniedException(
                $e,
                $registeredBucketName,
                $listingName
            );
        }

        // And in response we return the name generated by the generator for the needs of connection
        return (new GrantBucketAccessToReadOnlyRoleResponse())->setCreateBucketObjectName($newBucketDatabaseName);
    }
}
